name: Auto build & Release

on: push

jobs:
    release:
      runs-on: ${{ matrix.os }}

      strategy:
        matrix:
          os: [windows-latest]
      steps:
        - uses: actions/checkout@master
          with:
            ref: feature/github-actions  

        - uses: actions/setup-node@master
          with:
            node-version: 14.15.3

        - name: Install dependencies
          run: npm install

        - name: Build Electron
          run: npm run electron:build

        - name: Build/release Electron app
          uses: samuelmeuli/action-electron-builder@v1
          with:
            # GitHub token, automatically provided to the action
            # (No need to define this secret in the repo settings)
            github_token: ${{ secrets.github_token }}

            # If the commit is tagged with a version (e.g. "v1.0.0"),
            # release the app after building
            release: ${{ startsWith(github.ref, 'refs/tags/v') }}
